local  RUI = select(2, ...):unpack()
local E, L, V, P, G = unpack(ElvUI)

function RUI:ElvUIRedtuzk(name)
  --Profile Settings
  ElvDB["profiles"][name] = {
    ["actionbar"] = {
        ["bar1"] = {
            ["backdropSpacing"] = 1,
            ["buttonHeight"] = 33,
            ["buttonSize"] = 41,
            ["buttonSpacing"] = 1,
            ["buttons"] = 6,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["keepSizeRatio"] = false,
            ["paging"] = {
                ["ROGUE"] = "",
            },
            ["visibility"] = "",
        },
        ["bar2"] = {
            ["backdropSpacing"] = 1,
            ["buttonHeight"] = 31,
            ["buttonSize"] = 35,
            ["buttonSpacing"] = 1,
            ["buttons"] = 8,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["keepSizeRatio"] = false,
            ["visibility"] = " ",
        },
        ["bar3"] = {
            ["backdropSpacing"] = 1,
            ["buttonHeight"] = 28,
            ["buttonSpacing"] = 1,
            ["buttons"] = 7,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["keepSizeRatio"] = false,
            ["visibility"] = " ",
        },
        ["bar4"] = {
            ["backdrop"] = false,
            ["backdropSpacing"] = 1,
            ["buttonSpacing"] = 1,
            ["buttons"] = 8,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = false,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["point"] = "BOTTOMLEFT",
            ["visibility"] = " ",
        },
        ["bar5"] = {
            ["backdropSpacing"] = 1,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 2,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = false,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["visibility"] = "",
        },
        ["bar6"] = {
            ["backdropSpacing"] = 3,
            ["buttonSize"] = 34,
            ["buttonSpacing"] = 1,
            ["buttons"] = 7,
            ["buttonsPerRow"] = 1,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["visibility"] = " ",
        },
        ["bar7"] = {
            ["backdropSpacing"] = 1,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 2,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Gilroy Bold",
            ["macroFontOutline"] = "OUTLINE",
            ["macroTextPosition"] = "BOTTOM",
            ["macrotext"] = true,
            ["paging"] = {
                ["ROGUE"] = "",
            },
            ["visibility"] = "",
        },
        ["bar8"] = {
            ["buttonHeight"] = 27,
            ["buttonSize"] = 34,
            ["buttonSpacing"] = 1,
            ["buttons"] = 2,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyColor"] = {
                ["b"] = 0,
                ["g"] = 0.015686274509804,
            },
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["hotkeyTextPosition"] = "TOP",
            ["hotkeyTextYOffset"] = -2,
            ["hotkeytext"] = false,
            ["keepSizeRatio"] = false,
            ["visibility"] = "",
        },
        ["bar9"] = {
            ["buttonHeight"] = 27,
            ["buttonSize"] = 34,
            ["buttonSpacing"] = 1,
            ["buttons"] = 3,
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["countTextPosition"] = "BOTTOM",
            ["hotkeyFont"] = "Gilroy Bold",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["hotkeytext"] = false,
            ["keepSizeRatio"] = false,
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["backdropSpacing"] = 1,
            ["buttonSize"] = 25,
            ["buttonSpacing"] = 0,
            ["buttonsPerRow"] = 10,
            ["point"] = "RIGHT",
        },
        ["cooldown"] = {
            ["checkSeconds"] = true,
            ["fonts"] = {
                ["enable"] = true,
                ["font"] = "Gilroy Bold",
                ["fontSize"] = 14,
            },
            ["hhmmColor"] = {
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["hhmmThreshold"] = 150,
            ["mmssColor"] = {
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["mmssThreshold"] = 300,
        },
        ["font"] = "Gilroy Bold",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 12,
        ["noPowerColor"] = {
            ["g"] = 0.50196078431373,
            ["r"] = 0.50196078431373,
        },
        ["stanceBar"] = {
            ["backdropSpacing"] = 1,
            ["buttonHeight"] = 25,
            ["buttonSize"] = 33,
            ["enabled"] = false,
            ["keepSizeRatio"] = false,
            ["point"] = "BOTTOMRIGHT",
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["horizontalSpacing"] = 4,
            ["size"] = 38,
            ["timeFont"] = "Gilroy Bold",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 12,
        },
        ["cooldown"] = {
            ["checkSeconds"] = true,
            ["hhmmColor"] = {
                ["b"] = 1,
                ["g"] = 0.6156862745098,
                ["r"] = 0,
            },
            ["hhmmThreshold"] = 1440,
            ["minutesColor"] = {
                ["b"] = 0,
                ["g"] = 0.082352941176471,
            },
            ["mmssColor"] = {
                ["b"] = 1,
                ["g"] = 1,
                ["r"] = 1,
            },
            ["mmssColorIndicator"] = {
                ["g"] = 0.6156862745098,
                ["r"] = 0,
            },
            ["mmssThreshold"] = 3600,
            ["override"] = true,
            ["useIndicatorColor"] = true,
        },
        ["debuffs"] = {
            ["countFont"] = "Gilroy Bold",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["horizontalSpacing"] = 4,
            ["size"] = 38,
            ["timeFont"] = "Gilroy Bold",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 12,
        },
    },
    ["bags"] = {
        ["bagBar"] = {
            ["size"] = 53,
            ["spacing"] = 5,
        },
        ["bagWidth"] = 365,
        ["bankWidth"] = 365,
        ["clearSearchOnClose"] = true,
        ["countFont"] = "Gilroy Bold",
        ["countFontOutline"] = "OUTLINE",
        ["countFontSize"] = 15,
        ["itemLevelFont"] = "Gilroy Bold",
        ["itemLevelFontOutline"] = "OUTLINE",
        ["itemLevelFontSize"] = 11,
        ["moneyFormat"] = "CONDENSED",
        ["showAssignedColor"] = false,
        ["vendorGrays"] = {
            ["enable"] = true,
        },
    },
    ["chat"] = {
        ["editBoxPosition"] = "ABOVE_CHAT",
        ["emotionIcons"] = false,
        ["fade"] = false,
        ["fadeTabsNoBackdrop"] = false,
        ["font"] = "Gilroy Bold",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 11,
        ["panelBackdrop"] = "HIDEBOTH",
        ["panelColor"] = {
            ["a"] = 0.60000002384186,
            ["b"] = 0.054901960784314,
            ["g"] = 0.054901960784314,
            ["r"] = 0.054901960784314,
        },
        ["panelHeight"] = 220,
        ["panelHeightRight"] = 150,
        ["panelTabTransparency"] = true,
        ["panelWidth"] = 400,
        ["panelWidthRight"] = 399,
        ["pinVoiceButtons"] = false,
        ["hideVoiceButtons"] = true,
        ["tabFont"] = "Gilroy Bold",
        ["tabFontOutline"] = "OUTLINE",
        ["tabFontSize"] = 13,
        ["tabSelector"] = "ARROW2",
        ["tabSelectorColor"] = {
            ["b"] = 1,
            ["g"] = 0.69411764705882,
            ["r"] = 0,
        },
    },
    ["convertPages"] = true,
    ["cooldown"] = {
        ["fonts"] = {
            ["font"] = "Expressway",
        },
        ["hhmmColor"] = {
            ["b"] = 1,
            ["g"] = 1,
            ["r"] = 1,
        },
        ["mmssColor"] = {
            ["b"] = 1,
            ["g"] = 1,
            ["r"] = 1,
        },
        ["threshold"] = 2,
        ["useIndicatorColor"] = true,
    },
    ["databars"] = {
        ["colors"] = {
            ["experience"] = {
                ["a"] = 1,
            },
        },
        ["experience"] = {
            ["font"] = "Gilroy Bold",
            ["fontOutline"] = "OUTLINE",
            ["height"] = 12,
            ["textFormat"] = "PERCENT",
            ["width"] = 273,
        },
        ["reputation"] = {
            ["enable"] = true,
            ["font"] = "Gilroy Bold",
            ["fontOutline"] = "OUTLINE",
            ["height"] = 15,
            ["textFormat"] = "PERCENT",
            ["width"] = 204,
        },
        ["threat"] = {
            ["enable"] = false,
        },
    },
    ["datatexts"] = {
        ["font"] = "Gilroy Bold",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 14,
        ["panels"] = {
            ["Bottom Panel (RUI)"] = {
                [1] = "Ping",
                [2] = "Time",
                [3] = "Gold",
                ["enable"] = true,
            },
            ["BottomLeftMiniPanel"] = "Time",
            ["BottomRightMiniPanel"] = "Ping",
            ["LeftChatDataPanel"] = {
                ["enable"] = false,
                ["left"] = "",
                ["middle"] = "",
                ["right"] = "",
            },
            ["LeftMiniPanel"] = "",
            ["MinimapPanel"] = {
                ["enable"] = false,
            },
            ["RightChatDataPanel"] = {
                ["enable"] = false,
                ["left"] = "",
                ["middle"] = "",
                ["right"] = "",
            },
            ["RightMiniPanel"] = "",
            ["Top_Center"] = "",
        },
    },
    ["general"] = {
        ["afk"] = false,
        ["autoRepair"] = "PLAYER",
        ["backdropcolor"] = {
            ["b"] = 0.12549019607843,
            ["g"] = 0.12549019607843,
            ["r"] = 0.12549019607843,
        },
        ["backdropfadecolor"] = {
            ["a"] = 0.60000002384186,
            ["b"] = 0.054901960784314,
            ["g"] = 0.054901960784314,
            ["r"] = 0.054901960784314,
        },
        ["bottomPanel"] = false,
        ["decimalLength"] = 0,
        ["font"] = "Gilroy Bold",
        ["interruptAnnounce"] = "SAY",
        ["loginmessage"] = false,
        ["minimap"] = {
            ["icons"] = {
                ["mail"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["scale"] = 1.25,
                    ["texture"] = "Mail0",
                    ["yOffset"] = 0,
                },
            },
            ["locationFont"] = "Gilroy Bold",
            ["locationFontSize"] = 13,
            ["size"] = 202,
        },
        ["stickyFrames"] = false,
        ["totems"] = {
            ["growthDirection"] = "HORIZONTAL",
        },
        ["valuecolor"] = {
            ["b"] = 1,
            ["g"] = 1,
            ["r"] = 1,
        },
    },
    ["movers"] = {
        ["ActionBG_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,0,2",
        ["AlertFrameMover"] = "TOP,ElvUIParent,TOP,0,-230",
        ["AltPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-2,196",
        ["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-382,-395",
        ["ArtifactBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-40,-222",
        ["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-40,-222",
        ["BNETMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-5,376",
        ["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-147,-273",
        ["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,-2,129",
        ["BossHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-296,-433",
        ["BottomBG_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,241,251",
        ["Bottom_Panel_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,260,4",
        ["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-235,-28",
        ["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,2,366",
        ["ComboBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-1,303",
        ["DP_1_Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,303,429",
        ["DP_2_Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-10,7",
        ["DP_3_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,0,-1",
        ["DP_6_Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,8,8",
        ["DTB2_RUI Bottom Panel_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,0,4",
        ["DTPanelBottom Panel (RUI)Mover"] = "BOTTOM,ElvUIParent,BOTTOM,-1,2",
        ["Dashboard"] = "BOTTOM,ElvUIParent,BOTTOM,-34,458",
        ["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-235,-193",
        ["DigSiteProgressBarMover"] = "TOP,ElvUIParent,TOP,0,-249",
        ["DurabilityFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-391,-312",
        ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,2,322",
        ["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,-1,24",
        ["ElvAB_3"] = "BOTTOM,ElvUIParent,BOTTOM,2,293",
        ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,3",
        ["ElvAB_5"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,498,32",
        ["ElvAB_6"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-12,-400",
        ["ElvAB_7"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,431,32",
        ["ElvAB_8"] = "BOTTOM,ElvUIParent,BOTTOM,-215,310",
        ["ElvAB_9"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,630,310",
        ["ElvNP_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,403",
        ["ElvUF_FocusCastbarMover"] = "TOP,ElvUIParent,TOP,-338,-377",
        ["ElvUF_FocusMover"] = "TOP,ElvUIParent,TOP,-338,-356",
        ["ElvUF_PartyMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,468,-491",
        ["ElvUF_PetMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,563,337",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,2,267",
        ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-302,337",
        ["ElvUF_Raid10Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-435",
        ["ElvUF_Raid25Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,4,-258",
        ["ElvUF_Raid40Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,29,243",
        ["ElvUF_RaidMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,29,243",
        ["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,9,622",
        ["ElvUF_TargetCastbarMover"] = "TOP,ElvUIParent,TOP,0,-300",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,298,337",
        ["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-567,337",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-20,20",
        ["ElvUIBankMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,22,20",
        ["ElvUI_Raidcooldowns_Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,4",
        ["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-4",
        ["FlareMover"] = "TOP,ElvUIParent,TOP,0,202",
        ["FocusPowerBarMover"] = "TOP,ElvUIParent,TOP,-338,-371",
        ["GMMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,426,0",
        ["GhostFrameMover"] = "TOP,ElvUIParent,TOP,0,-147",
        ["HonorBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,419,8",
        ["LeftBG_Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,5,-187",
        ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,22,20",
        ["LevelUpBossBannerMover"] = "TOP,ElvUIParent,TOP,-4,-133",
        ["LootFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,7,-178",
        ["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-430",
        ["MMButtonsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-203",
        ["MarkMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-2,231",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-23,-28",
        ["MirrorTimer1Mover"] = "TOP,ElvUIParent,TOP,0,-30",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-148,-273",
        ["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,57",
        ["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,2,355",
        ["QuestTimerFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-67,-330",
        ["QuestWatchFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-238,-332",
        ["RaidBuffsCheckerPersonalFrame_MOVER"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-413,8",
        ["RaidMarkerBarAnchor"] = "BOTTOM,ElvUIParent,BOTTOM,226,310",
        ["RaidUtility_Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,277,0",
        ["ReputationBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-23,-232",
        ["RightBG_Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-10,26",
        ["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-20,20",
        ["SLE_BG_3_Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-20,20",
        ["SLE_BG_4_Mover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-20,20",
        ["SLE_DataPanel_3_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["SLE_DataPanel_4_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["SLE_DataPanel_5_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["SLE_DataPanel_6_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["SLE_DataPanel_7_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["SLE_DataPanel_8_Mover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,0,0",
        ["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,-233,312",
        ["SocialMenuMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,425,20",
        ["SquareMinimapButtonBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-20,-49",
        ["TalkingHeadFrameMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,22,218",
        ["TargetPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,298,339",
        ["TaxiButtonMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,160",
        ["TempEnchantMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-205",
        ["TimeManagerFrameMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-231,419",
        ["TooltipMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-253,20",
        ["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-15",
        ["Top_Center_Mover"] = "BOTTOM,ElvUIParent,BOTTOM,-260,4",
        ["TotemBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,207",
        ["UIBFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,8,-532",
        ["UIErrorsFrameMover"] = "TOP,ElvUIParent,TOP,0,-160",
        ["VOICECHAT"] = "TOPLEFT,ElvUIParent,TOPLEFT,211,-80",
        ["VehicleLeaveButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,118",
        ["VehicleSeatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-253,20",
        ["WatchFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-123,-250",
        ["ZoneAbility"] = "BOTTOM,ElvUIParent,BOTTOM,-300,193",
    },
    ["nameplates"] = {
        ["filters"] = {
            ["ElvUI_Target"] = {
                ["triggers"] = {
                    ["enable"] = false,
                },
            },
            ["Threat"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
        },
        ["statusbar"] = "Melli",
    },
    ["tooltip"] = {
        ["colorAlpha"] = 0.9,
        ["cursorAnchor"] = true,
        ["font"] = "Gilroy Bold",
        ["fontOutline"] = "OUTLINE",
        ["headerFontSize"] = 11,
        ["healthBar"] = {
            ["font"] = "Gilroy Bold",
            ["fontSize"] = 12,
            ["height"] = 4,
            ["statusPosition"] = "TOP",
            ["text"] = false,
        },
        ["smallTextFontSize"] = 11,
        ["textFontSize"] = 11,
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.094117647058824,
                ["g"] = 0.07843137254902,
                ["r"] = 0.30980392156863,
            },
            ["castClassColor"] = true,
            ["castColor"] = {
                ["b"] = 0.18823529411765,
                ["g"] = 0.82352941176471,
                ["r"] = 1,
            },
            ["castNoInterrupt"] = {
                ["b"] = 0.25098039215686,
                ["g"] = 0.25098039215686,
                ["r"] = 0.78039215686274,
            },
            ["castbar_backdrop"] = {
                ["b"] = 0.13725490196078,
                ["g"] = 0.13725490196078,
                ["r"] = 0.13725490196078,
            },
            ["classResources"] = {
                ["comboPoints"] = {
                    [1] = {
                        ["b"] = 0.14901960784314,
                        ["g"] = 0.18039215686275,
                        ["r"] = 0.86666666666667,
                    },
                    [2] = {
                        ["b"] = 0.019607843137255,
                        ["g"] = 0.44313725490196,
                        ["r"] = 0.84705882352941,
                    },
                    [3] = {
                        ["b"] = 0,
                        ["g"] = 0.56078431372549,
                        ["r"] = 0.74117647058824,
                    },
                    [4] = {
                        ["b"] = 0,
                        ["g"] = 0.72156862745098,
                        ["r"] = 0.56078431372549,
                    },
                    [5] = {
                        ["b"] = 0.38823529411765,
                        ["g"] = 0.85882352941176,
                        ["r"] = 0.1843137254902,
                    },
                },
            },
            ["colorhealthbyvalue"] = false,
            ["customcastbarbackdrop"] = true,
            ["customhealthbackdrop"] = true,
            ["frameGlow"] = {
                ["mouseoverGlow"] = {
                    ["texture"] = "Melli",
                },
                ["targetGlow"] = {
                    ["enable"] = false,
                },
            },
            ["health"] = {
                ["b"] = 0.11764705882353,
                ["g"] = 0.11764705882353,
                ["r"] = 0.11764705882353,
            },
            ["health_backdrop"] = {
                ["b"] = 0.098039215686274,
                ["g"] = 0.098039215686274,
                ["r"] = 0.098039215686274,
            },
            ["healthclass"] = true,
            ["power"] = {
                ["ENERGY"] = {
                    ["b"] = 0.4078431372549,
                    ["g"] = 0.95686274509804,
                    ["r"] = 1,
                },
                ["FOCUS"] = {
                    ["b"] = 0.25098039215686,
                    ["g"] = 0.49803921568628,
                    ["r"] = 1,
                },
                ["MANA"] = {
                    ["b"] = 1,
                    ["g"] = 0.49803921568628,
                    ["r"] = 0.098039215686274,
                },
                ["RAGE"] = {
                    ["b"] = 0.14117647058823,
                    ["g"] = 0.10196078431373,
                    ["r"] = 1,
                },
            },
            ["selection"] = {
                [3] = {
                    ["g"] = 0.70196078431373,
                },
            },
            ["tapped"] = {
                ["b"] = 0.54509803921569,
                ["g"] = 0.54509803921569,
                ["r"] = 0.54509803921569,
            },
        },
        ["font"] = "Gilroy Bold",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 13,
        ["smartRaidFilter"] = false,
        ["smoothbars"] = true,
        ["statusbar"] = "Melli",
        ["units"] = {
            ["arena"] = {
                ["buffs"] = {
                    ["countFont"] = "Gilroy Bold",
                    ["yOffset"] = 14,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                    },
                    ["height"] = 20,
                    ["width"] = 210,
                },
                ["debuffs"] = {
                    ["countFont"] = "Gilroy Bold",
                    ["xOffset"] = -1,
                    ["yOffset"] = -15,
                },
                ["height"] = 56,
                ["name"] = {
                    ["text_format"] = "[name:medium]",
                },
                ["power"] = {
                    ["height"] = 7,
                },
                ["pvpTrinket"] = {
                    ["size"] = 44,
                },
                ["width"] = 210,
            },
            ["assist"] = {
                ["enable"] = false,
                ["targetsGroup"] = {
                    ["enable"] = false,
                },
                ["threatStyle"] = "HEALTHBORDER",
            },
            ["focus"] = {
                ["buffs"] = {
                    ["countFont"] = "Gilroy Bold",
                    ["enable"] = true,
                    ["yOffset"] = 65,
                },
                ["castbar"] = {
                    ["customColor"] = {
                        ["color"] = {
                            ["b"] = 0,
                            ["g"] = 0.85490196078431,
                            ["r"] = 0.96078431372549,
                        },
                        ["colorInterrupted"] = {
                            ["b"] = 1,
                            ["g"] = 0,
                            ["r"] = 0.69019607843137,
                        },
                        ["useCustomBackdrop"] = true,
                    },
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontSize"] = 13,
                    },
                    ["format"] = "CURRENTMAX",
                    ["height"] = 22,
                    ["iconAttached"] = false,
                    ["iconPosition"] = "RIGHT",
                    ["iconXOffset"] = 1,
                    ["iconYOffset"] = -12,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                },
                ["customTexts"] = {
                    ["!health"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 16,
                        ["text_format"] = "[health:percent]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 20,
                    },
                    ["!name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[name:short]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 20,
                    },
                },
                ["debuffs"] = {
                    ["enable"] = false,
                },
                ["disableTargetGlow"] = true,
                ["height"] = 20,
                ["name"] = {
                    ["text_format"] = " ",
                },
                ["power"] = {
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 108,
                    ["height"] = 4,
                    ["width"] = "inset",
                },
                ["threatStyle"] = "NONE",
            },
            ["party"] = {
                ["buffIndicator"] = {
                    ["enable"] = false,
                    ["size"] = 10,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 13,
                    ["perrow"] = 1,
                    ["priority"] = "TurtleBuffs",
                    ["sizeOverride"] = 24,
                    ["sortDirection"] = "ASCENDING",
                    ["sortMethod"] = "INDEX",
                    ["xOffset"] = -26,
                    ["yOffset"] = 27,
                },
                ["customTexts"] = {
                    ["!Level"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 15,
                        ["text_format"] = "[difficultycolor][smartlevel]",
                        ["xOffset"] = 3,
                        ["yOffset"] = -3,
                    },
                    ["!Name"] = {
                        ["attachTextTo"] = "Frame",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 15,
                        ["text_format"] = "||cffffffff[RUI:leadericon][name:short] ",
                        ["xOffset"] = 2,
                        ["yOffset"] = 21,
                    },
                    ["Health Text"] = {
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 15,
                        ["text_format"] = "[status]",
                        ["xOffset"] = -1,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["attachTo"] = "HEALTH",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 15,
                    ["perrow"] = 3,
                    ["sizeOverride"] = 25,
                    ["xOffset"] = 3,
                },
                ["groupBy"] = "ROLE",
                ["growthDirection"] = "DOWN_LEFT",
                ["health"] = {
                    ["position"] = "CENTER",
                    ["text_format"] = "",
                    ["xOffset"] = 72,
                },
                ["height"] = 27,
                ["horizontalSpacing"] = 3,
                ["name"] = {
                    ["position"] = "TOP",
                    ["text_format"] = " ",
                    ["xOffset"] = -50,
                    ["yOffset"] = 8,
                },
                ["petsGroup"] = {
                    ["anchorPoint"] = "BOTTOM",
                },
                ["portrait"] = {
                    ["overlay"] = true,
                    ["rotation"] = 170,
                    ["width"] = 62,
                    ["xOffset"] = 0.31,
                },
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["height"] = 5,
                    ["offset"] = 2,
                    ["position"] = "BOTTOM",
                    ["text_format"] = " ",
                    ["width"] = "spaced",
                    ["xOffset"] = 0,
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                    ["position"] = "TOPRIGHT",
                },
                ["raidWideSorting"] = true,
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["size"] = 20,
                    ["xOffset"] = 52,
                    ["yOffset"] = 13,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "Gilroy Bold",
                },
                ["showPlayer"] = false,
                ["startFromCenter"] = true,
                ["targetsGroup"] = {
                    ["anchorPoint"] = "BOTTOM",
                    ["name"] = {
                        ["text_format"] = "||cffFFFFFF[name:veryshort]||r",
                    },
                    ["width"] = 43,
                    ["xOffset"] = -93,
                    ["yOffset"] = 28,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["verticalSpacing"] = 18,
                ["visibility"] = "[@raid6,exists][nogroup]hide;show",
                ["width"] = 141,
            },
            ["pet"] = {
                ["buffIndicator"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOM",
                    ["sizeOverride"] = 33,
                    ["spacing"] = 5,
                    ["xOffset"] = 16,
                    ["yOffset"] = -2,
                },
                ["castbar"] = {
                    ["enable"] = false,
                    ["width"] = 65,
                },
                ["customTexts"] = {
                    ["!Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 13,
                        ["text_format"] = "[happiness:icon][name:veryshort]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["fader"] = {
                    ["range"] = false,
                },
                ["healPrediction"] = {
                    ["enable"] = false,
                },
                ["health"] = {
                    ["position"] = "BOTTOM",
                    ["text_format"] = " ",
                },
                ["height"] = 18,
                ["name"] = {
                    ["text_format"] = " ",
                    ["xOffset"] = 1,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 3,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["width"] = 65,
            },
            ["pettarget"] = {
                ["height"] = 15,
                ["power"] = {
                    ["width"] = "inset",
                },
                ["width"] = 129,
            },
            ["player"] = {
                ["RestIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 14,
                    ["sizeOverride"] = 38,
                    ["xOffset"] = -10,
                },
                ["castbar"] = {
                    ["format"] = "CURRENTMAX",
                    ["height"] = 25,
                    ["icon"] = false,
                    ["iconAttached"] = false,
                    ["iconAttachedTo"] = "Castbar",
                    ["iconSize"] = 34,
                    ["iconXOffset"] = 124,
                    ["iconYOffset"] = -32,
                    ["latency"] = false,
                    ["spark"] = false,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["tickColor"] = {
                        ["a"] = 1,
                    },
                    ["width"] = 230,
                },
                ["classbar"] = {
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 246,
                    ["height"] = 9,
                    ["spacing"] = -1,
                },
                ["customTexts"] = {
                    ["!Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 18,
                        ["text_format"] = "[RUI:leadericon][name]",
                        ["xOffset"] = 4,
                        ["yOffset"] = 18,
                    },
                    ["!Percent"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 18,
                        ["text_format"] = "||cffffffff[health:percent]||r",
                        ["xOffset"] = 0,
                        ["yOffset"] = 18,
                    },
                    ["!Power"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 19,
                        ["text_format"] = "[power:RUIPower]",
                        ["xOffset"] = -1,
                        ["yOffset"] = 15,
                    },
                    ["Health2"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "||cffffffff[health:current]||r",
                        ["xOffset"] = -1,
                        ["yOffset"] = -1,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 14,
                    ["perrow"] = 7,
                    ["sizeOverride"] = 33,
                    ["sortMethod"] = "INDEX",
                    ["yOffset"] = 22,
                },
                ["health"] = {
                    ["position"] = "RIGHT",
                    ["text_format"] = " ",
                    ["xOffset"] = 0,
                    ["yOffset"] = 14,
                },
                ["height"] = 18,
                ["infoPanel"] = {
                    ["height"] = 16,
                    ["transparent"] = true,
                },
                ["name"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = " ",
                    ["xOffset"] = 4,
                    ["yOffset"] = 14,
                },
                ["portrait"] = {
                    ["camDistanceScale"] = 1.66,
                    ["overlay"] = true,
                    ["rotation"] = 340,
                    ["width"] = 73,
                },
                ["power"] = {
                    ["EnergyManaRegen"] = true,
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 246,
                    ["height"] = 11,
                    ["text_format"] = "[powercolor]",
                    ["xOffset"] = 0,
                    ["yOffset"] = -44,
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["size"] = 13,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["width"] = 240,
            },
            ["raid"] = {
                ["buffIndicator"] = {
                    ["size"] = 15,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontOutline"] = "NONE",
                    ["countFontSize"] = 4,
                    ["enable"] = true,
                    ["perrow"] = 1,
                    ["sizeOverride"] = 16,
                    ["yOffset"] = -17,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["enable"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 1,
                    ["priority"] = "SHOWMETHIS,Whitelist,Blacklist,Boss,RaidDebuffs,DungeonDebuffs,CCDebuffs,Dispellable",
                    ["sizeOverride"] = 20,
                    ["yOffset"] = 6,
                },
                ["growthDirection"] = "RIGHT_UP",
                ["health"] = {
                    ["orientation"] = "VERTICAL",
                    ["position"] = "CENTER",
                    ["text_format"] = "[status]",
                    ["xOffset"] = 0,
                },
                ["height"] = 50,
                ["horizontalSpacing"] = 1,
                ["name"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "||cffffffff[name:veryshort] [difficultycolor]",
                    ["yOffset"] = 5,
                },
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["height"] = 5,
                    ["position"] = "BOTTOM",
                    ["width"] = "inset",
                    ["xOffset"] = 8,
                    ["yOffset"] = -4,
                },
                ["raidRoleIcons"] = {
                    ["yOffset"] = 0,
                },
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["size"] = 13,
                    ["xOffset"] = 25,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                },
                ["readycheckIcon"] = {
                    ["position"] = "CENTER",
                    ["size"] = 15,
                    ["yOffset"] = 0,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["verticalSpacing"] = 1,
                ["width"] = 65,
            },
            ["raid40"] = {
                ["buffIndicator"] = {
                    ["size"] = 10,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontOutline"] = "NONE",
                    ["countFontSize"] = 4,
                    ["enable"] = true,
                    ["perrow"] = 1,
                    ["sizeOverride"] = 14,
                    ["xOffset"] = 18,
                    ["yOffset"] = 15,
                },
                ["customTexts"] = {
                    ["Health Text"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 12,
                        ["text_format"] = "",
                        ["xOffset"] = 37,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["enable"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 1,
                    ["priority"] = "SHOWMETHIS,Whitelist,Blacklist,Boss,RaidDebuffs,DungeonDebuffs,CCDebuffs,Dispellable",
                    ["sizeOverride"] = 19,
                    ["yOffset"] = 5,
                },
                ["growthDirection"] = "DOWN_RIGHT",
                ["health"] = {
                    ["orientation"] = "VERTICAL",
                    ["position"] = "CENTER",
                    ["text_format"] = "[status]",
                    ["xOffset"] = 0,
                },
                ["height"] = 46,
                ["horizontalSpacing"] = 1,
                ["name"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "||cffffffff[name:veryshort] [difficultycolor]",
                    ["xOffset"] = 1,
                    ["yOffset"] = 1,
                },
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["height"] = 4,
                    ["position"] = "BOTTOM",
                    ["xOffset"] = 8,
                    ["yOffset"] = -4,
                },
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["enable"] = false,
                    ["size"] = 13,
                    ["xOffset"] = 25,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                },
                ["readycheckIcon"] = {
                    ["position"] = "CENTER",
                    ["size"] = 15,
                    ["yOffset"] = 0,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["verticalSpacing"] = 1,
                ["visibility"] = "[@raid21,noexists] hide;show",
                ["width"] = 49,
            },
            ["raidpet"] = {
                ["numGroups"] = 1,
                ["startFromCenter"] = true,
                ["threatStyle"] = "HEALTHBORDER",
            },
            ["tank"] = {
                ["enable"] = false,
                ["threatStyle"] = "HEALTHBORDER",
            },
            ["target"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["countFont"] = "Gilroy Bold",
                    ["numrows"] = 5,
                    ["perrow"] = 10,
                    ["priority"] = "",
                    ["sizeOverride"] = 23,
                    ["sortDirection"] = "ASCENDING",
                    ["xOffset"] = -240,
                    ["yOffset"] = -21,
                },
                ["castbar"] = {
                    ["format"] = "CURRENTMAX",
                    ["height"] = 25,
                    ["icon"] = false,
                    ["spark"] = false,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["timeToHold"] = 1,
                    ["xOffsetText"] = 5,
                },
                ["customTexts"] = {
                    ["!Level"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 15,
                        ["text_format"] = "[difficultycolor][smartlevel][shortclassification]",
                        ["xOffset"] = 4,
                        ["yOffset"] = -1,
                    },
                    ["!Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 18,
                        ["text_format"] = "[RUI:leadericon][name:abbrev]",
                        ["xOffset"] = 4,
                        ["yOffset"] = 18,
                    },
                    ["!Percent"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 18,
                        ["text_format"] = "||cffffffff[health:percent]||r",
                        ["xOffset"] = 0,
                        ["yOffset"] = 18,
                    },
                    ["Health2"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "||cffffffff[health:current:shortvalue]||r",
                        ["xOffset"] = -1,
                        ["yOffset"] = -1,
                    },
                    ["PowerText"] = {
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[mouseover]||cffffffff [power:currentreal] [powercolor]/ ||cffffffff[power:max] [powercolor]< ||cffffffff[power:percentreal]",
                        ["xOffset"] = -2,
                        ["yOffset"] = -25,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "Gilroy Bold",
                    ["maxDuration"] = 0,
                    ["numrows"] = 2,
                    ["perrow"] = 7,
                    ["priority"] = "Personal",
                    ["sizeOverride"] = 33,
                    ["sortDirection"] = "ASCENDING",
                    ["sortMethod"] = "PLAYER",
                    ["yOffset"] = 22,
                },
                ["health"] = {
                    ["text_format"] = " ",
                    ["xOffset"] = 0,
                    ["yOffset"] = 14,
                },
                ["height"] = 18,
                ["name"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = " ",
                    ["xOffset"] = 4,
                    ["yOffset"] = 14,
                },
                ["portrait"] = {
                    ["camDistanceScale"] = 2.4,
                    ["overlay"] = true,
                    ["rotation"] = 340,
                    ["width"] = 150,
                },
                ["power"] = {
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 80,
                    ["height"] = 4,
                    ["strataAndLevel"] = {
                        ["frameLevel"] = 2,
                        ["frameStrata"] = "HIGH",
                    },
                    ["text_format"] = "[powercolor]",
                    ["width"] = "inset",
                    ["xOffset"] = 6,
                    ["yOffset"] = -58,
                },
                ["raidRoleIcons"] = {
                    ["enable"] = false,
                    ["xOffset"] = 55,
                    ["yOffset"] = -7,
                },
                ["raidicon"] = {
                    ["size"] = 20,
                    ["xOffset"] = -4,
                    ["yOffset"] = 12,
                },
                ["threatStyle"] = "NONE",
                ["width"] = 240,
            },
            ["targettarget"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOM",
                    ["sizeOverride"] = 33,
                    ["xOffset"] = 16,
                    ["yOffset"] = -2,
                },
                ["customTexts"] = {
                    ["!Name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 15,
                        ["text_format"] = "||cffffffff[name:veryshort]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["enable"] = false,
                },
                ["height"] = 18,
                ["name"] = {
                    ["text_format"] = " ",
                    ["xOffset"] = 1,
                    ["yOffset"] = 19,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 3,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["width"] = 65,
            },
        },
    },
  }

  --Global settings
  --[[ElvDB["global"] = {
    ["datatexts"] = {
        ["customPanels"] = {
            ["Bottom Panel (RUI)"] = {
                ["backdrop"] = true,
                ["border"] = true,
                ["fonts"] = {
                    ["enable"] = false,
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                    ["fontSize"] = 12,
                },
                ["frameLevel"] = 1,
                ["frameStrata"] = "LOW",
                ["growth"] = "HORIZONTAL",
                ["height"] = 22,
                ["mouseover"] = false,
                ["name"] = "Bottom Panel (RUI)",
                ["numPoints"] = 3,
                ["panelTransparency"] = false,
                ["textJustify"] = "CENTER",
                ["tooltipAnchor"] = "ANCHOR_TOPLEFT",
                ["tooltipXOffset"] = -17,
                ["tooltipYOffset"] = 4,
                ["visibility"] = "[petbattle] hide;show",
                ["width"] = 282,
            },
        },
        ["settings"] = {
            ["Gold"] = {
                ["goldCoins"] = false,
                ["goldFormat"] = "SHORTINT",
            },
        },
    },
    ["general"] = {
        ["fadeMapWhenMoving"] = false,
        ["mapAlphaWhenMoving"] = 1,
        ["smallerWorldMapScale"] = 0.6,
    },
  }]]


  --Private Settings
    --[[E.private["general"]["chatBubbleFont"] = "Gilroy Bold"
    E.private["general"]["chatBubbleFontOutline"] = "OUTLINE"
    E.private["general"]["chatBubbleFontSize"] = 12
    E.private["general"]["chatBubbles"] = "nobackdrop"
    E.private["general"]["dmgfont"] = "Gilroy Bold"
    E.private["general"]["glossTex"] = "Melli"
    E.private["general"]["namefont"] = "Gilroy Bold"
    E.private["general"]["normTex"] = "Melli"
    E.private["install_complete"] = 1
    E.private["nameplates"]["enable"] = false]]



  E.data:SetProfile(name)
end

function RUI:RaidFrameStyle(style)
  if style == "vertical" then
    ElvDB["profiles"][E.private[RUI.PluginName].profileName]["movers"]["ElvUF_Raid40Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,22,-261"
    ElvDB["profiles"][E.private[RUI.PluginName].profileName]["movers"]["ElvUF_RaidMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,22,-261"
    E.db["unitframe"]["units"]["raid40"] = {
                ["buffIndicator"] = {
                    ["enable"] = false,
                    ["size"] = 10,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 4,
                    ["perrow"] = 1,
                    ["sizeOverride"] = 14,
                    ["xOffset"] = 18,
                    ["yOffset"] = 16,
                },
                ["classbar"] = {
                    ["enable"] = false,
                },
                ["debuffs"] = {
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 8,
                    ["enable"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 1,
                    ["priority"] = "Blacklist,Dispellable",
                    ["sizeOverride"] = 14,
                    ["xOffset"] = -15,
                },
                ["groupsPerRowCol"] = 8,
                ["growthDirection"] = "DOWN_RIGHT",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "CENTER",
                    ["text_format"] = "[status]",
                    ["xOffset"] = 0,
                },
                ["height"] = 15,
                ["horizontalSpacing"] = 1,
                ["name"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "||cffffffff[name] [difficultycolor] [smartlevel]",
                    ["xOffset"] = 121,
                },
                ["numGroups"] = 8,
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["height"] = 4,
                    ["position"] = "BOTTOM",
                    ["width"] = "spaced",
                    ["xOffset"] = 8,
                    ["yOffset"] = -4,
                },
                ["raidWideSorting"] = true,
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["size"] = 13,
                    ["xOffset"] = -15,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "CENTER",
                    ["position"] = "CENTER",
                    ["size"] = 15,
                    ["yOffset"] = 0,
                },
                ["startFromCenter"] = true,
                ["verticalSpacing"] = 1,
                ["visibility"] = "[@raid31,noexists] hide;show",
                ["width"] = 120,
    }
    E.db["unitframe"]["units"]["raid"] = {
                ["buffIndicator"] = {
                    ["enable"] = false,
                    ["profileSpecific"] = true,
                    ["size"] = 10,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 8,
                    ["perrow"] = 1,
                    ["sizeOverride"] = 21,
                    ["xOffset"] = 38,
                    ["yOffset"] = 12,
                },
                ["classbar"] = {
                    ["enable"] = false,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontSize"] = 11,
                    ["enable"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 1,
                    ["priority"] = "Blacklist,Dispellable",
                    ["sizeOverride"] = 14,
                    ["xOffset"] = 51,
                },
                ["groupSpacing"] = 1,
                ["groupsPerRowCol"] = 6,
                ["growthDirection"] = "DOWN_RIGHT",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "CENTER",
                    ["text_format"] = "[status]",
                    ["xOffset"] = 1,
                    ["yOffset"] = 0,
                },
                ["height"] = 20,
                ["horizontalSpacing"] = 0,
                ["name"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "||cffffffff[name][difficultycolor] [smartlevel]",
                    ["xOffset"] = 121,
                    ["yOffset"] = -2,
                },
                ["numGroups"] = 8,
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["enable"] = false,
                    ["height"] = 4,
                    ["position"] = "BOTTOM",
                    ["width"] = "spaced",
                    ["xOffset"] = 8,
                    ["yOffset"] = -4,
                },
                ["raidWideSorting"] = true,
                ["raidicon"] = {
                    ["attachTo"] = "LEFT",
                    ["size"] = 13,
                    ["xOffset"] = -15,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["duration"] = {
                        ["color"] = {
                            ["b"] = 1,
                            ["g"] = 1,
                        },
                        ["position"] = "TOPRIGHT",
                    },
                    ["enable"] = false,
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                    ["size"] = 20,
                    ["xOffset"] = 50,
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "BOTTOM",
                },
                ["startFromCenter"] = true,
                ["verticalSpacing"] = 1,
                ["visibility"] = "[@raid6,noexists][@raid31,exists] hide;show",
                ["width"] = 120,
    }
  elseif style == "grid" then
    ElvDB["profiles"][E.private[RUI.PluginName].profileName]["movers"]["ElvUF_Raid40Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,29,243"
    ElvDB["profiles"][E.private[RUI.PluginName].profileName]["movers"]["ElvUF_RaidMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,29,243"
    E.db["unitframe"]["units"]["raid40"] = {
                ["buffIndicator"] = {
                    ["size"] = 10,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontOutline"] = "NONE",
                    ["countFontSize"] = 4,
                    ["enable"] = true,
                    ["perrow"] = 1,
                    ["sizeOverride"] = 14,
                    ["xOffset"] = 18,
                    ["yOffset"] = 15,
                },
                ["customTexts"] = {
                    ["Health Text"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Gilroy Bold",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "CENTER",
                        ["size"] = 12,
                        ["text_format"] = "",
                        ["xOffset"] = 37,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["enable"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 1,
                    ["priority"] = "SHOWMETHIS,Whitelist,Blacklist,Boss,RaidDebuffs,DungeonDebuffs,CCDebuffs,Dispellable",
                    ["sizeOverride"] = 19,
                    ["yOffset"] = 5,
                },
                ["growthDirection"] = "DOWN_RIGHT",
                ["health"] = {
                    ["orientation"] = "VERTICAL",
                    ["position"] = "CENTER",
                    ["text_format"] = "[status]",
                    ["xOffset"] = 0,
                },
                ["height"] = 46,
                ["horizontalSpacing"] = 1,
                ["name"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "||cffffffff[name:veryshort] [difficultycolor]",
                    ["xOffset"] = 2,
                    ["yOffset"] = 6,
                },
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["height"] = 4,
                    ["position"] = "BOTTOM",
                    ["xOffset"] = 8,
                    ["yOffset"] = -4,
                },
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["enable"] = false,
                    ["size"] = 13,
                    ["xOffset"] = 25,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                },
                ["readycheckIcon"] = {
                    ["position"] = "CENTER",
                    ["size"] = 15,
                    ["yOffset"] = 0,
                },
                ["verticalSpacing"] = 1,
                ["visibility"] = "[@raid26,noexists] hide;show",
                ["width"] = 49,
    }
    E.db["unitframe"]["units"]["raid"] = {
                ["buffIndicator"] = {
                    ["size"] = 15,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "Gilroy Bold",
                    ["countFontOutline"] = "NONE",
                    ["countFontSize"] = 4,
                    ["enable"] = true,
                    ["perrow"] = 1,
                    ["sizeOverride"] = 16,
                    ["yOffset"] = -17,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "CENTER",
                    ["countFont"] = "Gilroy Bold",
                    ["enable"] = true,
                    ["maxDuration"] = 0,
                    ["perrow"] = 1,
                    ["priority"] = "SHOWMETHIS,Whitelist,Blacklist,Boss,RaidDebuffs,DungeonDebuffs,CCDebuffs,Dispellable",
                    ["sizeOverride"] = 20,
                    ["yOffset"] = 6,
                },
                ["growthDirection"] = "RIGHT_UP",
                ["health"] = {
                    ["orientation"] = "VERTICAL",
                    ["position"] = "CENTER",
                    ["text_format"] = "[status]",
                    ["xOffset"] = 0,
                },
                ["height"] = 50,
                ["horizontalSpacing"] = 1,
                ["name"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "||cffffffff[name:veryshort] [difficultycolor]",
                    ["yOffset"] = 5,
                },
                ["power"] = {
                    ["attachTextTo"] = "Frame",
                    ["height"] = 5,
                    ["position"] = "BOTTOM",
                    ["width"] = "inset",
                    ["xOffset"] = 8,
                    ["yOffset"] = -4,
                },
                ["raidRoleIcons"] = {
                    ["yOffset"] = 0,
                },
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["size"] = 13,
                    ["xOffset"] = 25,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "Gilroy Bold",
                    ["fontOutline"] = "OUTLINE",
                },
                ["readycheckIcon"] = {
                    ["position"] = "CENTER",
                    ["size"] = 15,
                    ["yOffset"] = 0,
                },
                ["threatStyle"] = "HEALTHBORDER",
                ["verticalSpacing"] = 1,
                ["width"] = 65,
    }
  end
  PluginInstallStepComplete.message = "Raid Frame Style Set"
  PluginInstallStepComplete:Show()
end
